### ISSUE TITLE
All Clear (AC) needed!

### ISSUE THREAD

**Issue by de04080** [adityar224/DigitalCalculator#3]
Hello, you replaced the `All Clear` key by a `Clear` key, in the last build 1.1.0.

As a result I have to press clear a zillion times, after each operation, to pass a new one.

I don't understand this decision.

Please revert this change, or add both an `AC` key & `C` key.

**Comment by cyber199** [comment]
Would it not be an idea to have just a tap act to backspace one number, but holding clear performs an all-clear?

**Comment by adeeteya** [comment]
@cyber199 @x1040 Have now added an option to perform all clear by long pressing the clear button.
